### ISSUE TITLE
Does only work for x86 python dists

### ISSUE THREAD

**Issue by wiberg71** [jondy/IMessageFilter#1]
I noticed that the code only worked on x86 python version. Since I had a x64 version I started to dig into the problem. I needed to recompile the msgfilter.c and build a x64 version. After doing so I noticed that no functions were exported in the dll. I had to add 

extern __declspec(dllexport) in front of the register_message_filter and revoke_message_filter functions

Then I started to test the dll by running __init__.py as script.

if __name__ == '__main__':
    windll.ole32.CoInitialize(0)
    CMessageFilter.Register()
    CMessageFilter.Revoke()
    windll.ole32.CoUninitialize()

Here I had to change the  CMessageFilter.Register() to  CMessageFilter.register() and  CMessageFilter.Revoke() to  CMessageFilter.revoke()

Now it worked. .

One more small thing. If you try use the library without importing comtypes the register crashes with access violation.

Thank you for sharing this. Without our code I would never been able to solve the com communication properly.

**Comment by Pukinn** [comment]
@wiberg71 I try to do the same thing, but I have no experience with C. I tried do download the current master commit c9ad0215222c2442c968dd773532d32fa4e5a8cd and build it with `x86_64-w64-mingw32-gcc`. In this commit your fixes should be included, right?

build and install with pip does work and the msgfilter.dll exists, but a call of `CMessageFilter.register()` fails:

```
>>> import comtypes
>>> from imessagefilter import CMessageFilter
>>> CMessageFilter.register()
Traceback (most recent call last):
  File "<python-input-2>", line 1, in <module>
    CMessageFilter.register()
    ~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Program Files\Python313\Lib\site-packages\imessagefilter\__init__.py", line 17, in register
    cls.msgfilter = windll.LoadLibrary(os.path.normpath(filename))
                    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python313\Lib\ctypes\__init__.py", line 471, in LoadLibrary
    return self._dlltype(name)
           ~~~~~~~~~~~~~^^^^^^
  File "C:\Program Files\Python313\Lib\ctypes\__init__.py", line 390, in __init__
    self._handle = _dlopen(self._name, mode)
                   ~~~~~~~^^^^^^^^^^^^^^^^^^
FileNotFoundError: Could not find module 'msgfilter.dll' (or one of its dependencies). Try using the full path with constructor syntax.
```

Do you have any hints, or an other way to use the message filter?
